# Generated by Django 4.1.2 on 2023-06-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('nombre_cliente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_mascota', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('telefono', models.CharField(max_length=45)),
                ('fecha_reserva', models.DateField()),
                ('hora_reserva', models.TimeField()),
                ('raza', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(db_column='idServicio', primary_key=True, serialize=False)),
                ('servicio', models.CharField(max_length=50)),
            ],
        ),
    ]
