# Generated by Django 4.1.2 on 2023-06-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='servicios',
            field=models.ManyToManyField(to='mascotas.servicio'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='precio',
            field=models.IntegerField(max_length=8, null=True),
        ),
    ]
